/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class Registrar extends javax.swing.JFrame {
    private Usuario u;
    boolean conectado;
    DAO d = new DAO();
    private Credencial credencial;
    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        this.setTitle("Mantenedor de Usuarios");
        this.setLocationRelativeTo(null);        
        ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/icono.png"));
        setIconImage(img.getImage());        
    }
    
    public void credencial(Credencial c){
        this.credencial = c;
    }     
    
    private void showM(boolean m){
        jTextField1.setEnabled(m);
        jTextField2.setEnabled(m);
        txtnom.setEnabled(m);
        txtape.setEnabled(m);
        jRadioButton1.setEnabled(m);
        jRadioButton2.setEnabled(m);
        cboesp.setEnabled(m);
        jButton1.setEnabled(m);
        jButton2.setEnabled(m);        
    }
    
    private void cleanM(){
        txtusu.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        txtnom.setText("");
        txtape.setText("");
        jRadioButton1.setSelected(true);
        cboesp.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboesp = new javax.swing.JComboBox<>();
        txtape = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtusu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANTENEDOR DE USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, -1));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel4.setText("REPETIR CONTRASEÑA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel5.setText("  NOMBRE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel6.setText("APELLIDO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 20));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel7.setText("PERFIL:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, 20));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel8.setText("ESPECILIDAD:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        cboesp.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        cboesp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE...", "Pediatría", "Nutriología", "Dermatología", "Cardiología" }));
        cboesp.setEnabled(false);
        getContentPane().add(cboesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));

        txtape.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        txtape.setEnabled(false);
        txtape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapeKeyTyped(evt);
            }
        });
        getContentPane().add(txtape, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, -1));

        txtnom.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        txtnom.setEnabled(false);
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, -1));

        txtusu.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        txtusu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuKeyTyped(evt);
            }
        });
        getContentPane().add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/separador.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 10, -1));

        jButton1.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jButton1.setText(" ");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 130, -1));

        jButton2.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial Narrow", 0, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ico_eliminar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 20, 20));
        jButton3.setBorder(null);
        jButton3.setVisible(false);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jTextField1.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, -1));

        jTextField2.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("DOCTOR");
        jRadioButton1.setEnabled(false);
        jRadioButton1.setOpaque(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jRadioButton2.setText("OBSERVADOR");
        jRadioButton2.setEnabled(false);
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flogin.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("ConectarBD");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("DesconectarBD");
        jMenu2.setEnabled(false);
        jMenu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // CONECTAR BD
        if(jMenu1.isEnabled()){
            if(conectado==false){
                conectado=true;
                d.conectar();
                JOptionPane.showMessageDialog(this, "<html><b> ¡Has sido conectado con éxito! </b></html>");
                jMenu1.setEnabled(false);
                jMenu2.setEnabled(true);
            }
        }

    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // DESCONECTAR BD
        if(jMenu2.isEnabled()){
            if(conectado==true){
                conectado=false;
                d.desconectar();
                JOptionPane.showMessageDialog(this, "<html><b> ¡Has sido desconectado con éxito! </b></html>");
                jMenu2.setEnabled(false);
                jMenu1.setEnabled(true);
                showM(false);
                cleanM();
                txtusu.setEnabled(true);
                jButton3.setVisible(false);
            }
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void txtusuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(jMenu1.isEnabled()){JOptionPane.showMessageDialog(this, "<html><b> ¡Error! </b><br>El servidor se encuentra desconectado.</html>");}
            else if(txtusu.getText().equalsIgnoreCase("MRivas")||txtusu.getText().equalsIgnoreCase("RFuentes")){JOptionPane.showMessageDialog(this, "<html><b> ¡Error! </b><br>No puede modificar está cuenta.</html>");}
            else if(d.consultarUsuario(txtusu.getText())==true){
                int dialogResult = JOptionPane.showConfirmDialog(this, "<html> <b> ¡El usuario ya existe! </b><br>¿Desea modificarlo?</html>", "", JOptionPane.YES_NO_OPTION);
                if (dialogResult == 0){
                    jButton1.setText("ACTUALIZAR");
                    u = d.cargarUsuario(txtusu.getText());
                    showM(true);
                    jButton3.setVisible(true);
                    txtusu.setEnabled(false);
                    txtnom.setText(u.getNombre());
                    txtape.setText(u.getApellido());
                    jTextField1.setText(u.getPassword());
                    jTextField2.setText(u.getPassword());                    
                    if(u.getPerfil().equals("2")){
                        jRadioButton1.setSelected(true);
                        jRadioButton1.setSelected(false);
                    }else{
                        jRadioButton2.setSelected(true);
                        jRadioButton2.setSelected(false);
                    }
                    cboesp.setSelectedIndex(Integer.parseInt(u.getEspecialidad()));
                }
            }else{
                jButton1.setText("CREAR");
                showM(true);
                txtusu.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtusuKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setEnabled(false);
        showM(false);
        cleanM();
        txtusu.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(this, "<html> <b> ¡Eliminar Usuario! </b><br>¿Desea eliminar el usuario: "+txtusu.getText()+"?</html>", "", JOptionPane.YES_NO_OPTION);
        if (dialogResult == 0){
            d.eliminarUsuario(txtusu.getText());
            JOptionPane.showMessageDialog(this, "<html><b> ¡Usuario Eliminado! </b><br>El usuario: "+txtusu.getText()+" se encuentra eliminado.</html>");
            showM(false);
            cleanM();
            txtusu.setEnabled(true);
            jButton3.setVisible(false);
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtusuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuKeyTyped
        char c = evt.getKeyChar();
	if(txtusu.getText().length() >= 20 || !(Character.isLetter(c)) ){ 
            evt.consume();
        } 
    }//GEN-LAST:event_txtusuKeyTyped

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        char c = evt.getKeyChar();
	if(txtnom.getText().length() >= 20 || !(Character.isLetter(c))){ 
            evt.consume();
        } 
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapeKeyTyped
        char c = evt.getKeyChar();
	if(txtape.getText().length() >= 20|| !(Character.isLetter(c))){ 
            evt.consume();
        } 
    }//GEN-LAST:event_txtapeKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = txtusu.getText();
        String password = jTextField1.getText();
        String nombre = txtnom.getText();
        String apellido = txtape.getText();
        String perfil="";
        if(jRadioButton1.isSelected()){
            perfil ="2";
        }else if(jRadioButton2.isSelected()){
            perfil="3";
        }
        String especialidad = Integer.toString(cboesp.getSelectedIndex()); 
        
        ArrayList<String> lista_errores = new ArrayList();
        if (usuario.trim().length() < 3) {
            lista_errores.add("Tiene que ingresar un usuario de 3 caracteres mínimo\n");
        }
        if (password.trim().length() < 8) {
            lista_errores.add("Tiene que ingresar una contraseña de 8 caracteres mínimo\n");
        }
        if (!(password.equalsIgnoreCase(jTextField2.getText()))) {
            lista_errores.add("Las contraseñas tienen que coincidir\n");
        }       
        if (nombre.trim().length() < 3) {
            lista_errores.add("Tiene que ingresar un nombre válido\n");
        }
        if (apellido.trim().length() < 3) {
            lista_errores.add("Tiene que ingresar un apellido válido\n");
        }
        if (especialidad.equalsIgnoreCase("0")) {
            lista_errores.add("Tiene que seleccionar una especialidad de médico\n");
        }
        
        if (lista_errores.isEmpty()) {

            if(jButton1.getText().equalsIgnoreCase("CREAR")){
                u = new Usuario(usuario,nombre,apellido,password,perfil,especialidad);
                d.registrarUsuario(u);
            }else{
                u = new Usuario(usuario,nombre,apellido,password,perfil,especialidad);
                d.modificarUsuario(u);
            }
            
            showM(false);
            cleanM();
            txtusu.setEnabled(true);
            jButton3.setVisible(false);
        }else{
            String errores = lista_errores.toString().replaceAll(",", "- ").replace("[","- ").replace("]","");
            javax.swing.JOptionPane.showMessageDialog(this,"Tiene los siguientes errores:"+"\n\n"+errores, "Error", 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Autentificacion a = new Autentificacion();        
        a.credencial(credencial);
        a.setEnabled(true);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboesp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
